version: '3.8'

services:
  jobmanager:
    image: flink:1.13
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.flink.size: 2048mb
        jobmanager.memory.process.size: 3072mb
  taskmanager:
    image: flink:1.13
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
        taskmanager.memory.flink.size: 2048mb
        taskmanager.memory.process.size: 3072mb
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

networks:
  default:
    name: lednet